Fix `'bool' object is not callable` when running galaxykit cli (#77)
introduced in https://github.com/ansible/galaxykit/pull/71#discussion_r972006872
`client.rbac_enabled` is a bool `@property`, thus not callable, removing parentheses

Fixes:

    Error: Galaxykit failed: Traceback (most recent call last):
    File "/home/runner/.local/bin/galaxykit", line 8, in <module>
        sys.exit(main())
    File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/command.py", line 632, in main
        if client.rbac_enabled():
    TypeError: 'bool' object is not callable