move GalaxyClientError back to utils, prevent circular imports
intended to fix

    Run galaxykit -s 'http://localhost:8002/api/galaxy/' -u admin -p admin collection list
    Traceback (most recent call last):
    File "/home/runner/.local/bin/galaxykit", line 5, in <module>
      from galaxykit.command import main
    File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/__init__.py", line 2, in <module>
      from .client import GalaxyClient
    File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/client.py", line 17, in <module>
      from . import collections
    File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/collections.py", line 13, in <module>
      from .client import GalaxyClientError
    ImportError: cannot import name 'GalaxyClientError' from partially initialized module 'galaxykit.client' (most likely due to a circular import) (/home/runner/.local/lib/python3.8/site-packages/galaxykit/client.py)