Keep python3.8 compatibility - argparse.BooleanOptionalAction is 3.9+; fix superuser creation
Introduced in #49,
fixes

    galaxykit -s 'http://localhost:8002/api/galaxy/' -u admin -p admin collection list

    Traceback (most recent call last):
      File "/home/runner/.local/bin/galaxykit", line 5, in <module>
        from galaxykit.command import main
      File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/command.py", line 212, in <module>
        "action": argparse.BooleanOptionalAction,
    AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
    Error: Process completed with exit code 1.

(https://github.com/ansible/ansible-hub-ui/pull/2233)